local M = {}

function M.apply(hi, c)
	-- Editor UI
	hi("Normal", { fg = c.foreground, bg = c.background })
	hi("NormalNC", { fg = c.foreground, bg = c.background })
	hi("CursorLine", { bg = c.dim_background })
	hi("CursorLineNr", { fg = c.foreground, bg = c.dim_background, bold = true })
	hi("LineNr", { fg = c.foreground, bg = c.dim_background })
	hi("LineNrAbove", { link = "LineNr" })
	hi("LineNrBelow", { link = "LineNr" })
	hi("SignColumn", { bg = c.dim_background })
	hi("FoldColumn", { fg = c.almost_foreground, bg = c.dim_background })
	hi("Directory", { fg = c.foreground, bold = true })
	hi("NonText", { fg = c.almost_foreground, bg = c.background })
	hi("Whitespace", { fg = c.almost_foreground })
	hi("EndOfBuffer", { fg = c.background, bg = c.background })
	hi("Title", { fg = c.foreground, bold = true })
	hi("Visual", { bg = c.darker_background })
	hi("VisualNOS", { bg = c.darker_background })
	hi("Folded", { fg = c.foreground, bg = c.dim_background, italic = true })
	hi("ColorColumn", { bg = c.darker_background })
	hi("Conceal", { fg = c.almost_foreground })
	hi("QuickFixLine", { bg = c.darker_background, bold = true })
	hi("WinSeparator", { fg = c.border, bg = c.background })
	hi("VertSplit", { link = "WinSeparator" })
	hi("MsgArea", { fg = c.foreground, bg = c.background })
	hi("MsgSeparator", { fg = c.foreground, bg = c.dim_background })

	-- Cursor (block bg + inverted fg so the character under the cursor stays
	-- visible; many terminals override the cursor color otherwise).
	hi("Cursor", { fg = c.background, bg = c.cursor })
	hi("lCursor", { fg = c.background, bg = c.cursor })
	hi("CursorIM", { fg = c.background, bg = c.cursor })
	hi("TermCursor", { fg = c.background, bg = c.cursor })
	hi("TermCursorNC", { fg = c.background, bg = c.almost_foreground })
	hi("CursorColumn", { bg = c.dim_background })
	hi("MatchParen", { fg = c.foreground, bg = c.darker_background, underline = true })

	-- Search
	hi("Search", { fg = c.foreground, bg = c.dim_background, bold = true })
	hi("CurSearch", { fg = c.foreground, bg = c.darker_background, bold = true })
	hi("IncSearch", { fg = c.foreground, bg = c.darker_background, bold = true })
	hi("Substitute", { fg = c.foreground, bg = c.darker_background, bold = true })

	-- Spell
	hi("SpellBad", { undercurl = true, sp = c.error })
	hi("SpellCap", { undercurl = true, sp = c.info })
	hi("SpellRare", { undercurl = true, sp = c.hint })
	hi("SpellLocal", { undercurl = true, sp = c.warning })

	-- Messages
	hi("ModeMsg", { fg = c.foreground, bg = c.background, bold = true })
	hi("MoreMsg", { fg = c.foreground, bg = c.background, bold = true })
	hi("ErrorMsg", { fg = c.error, bg = c.background, bold = true })
	hi("WarningMsg", { fg = c.warning, bg = c.background, bold = true })
	hi("InfoMsg", { fg = c.info, bg = c.background, bold = true })
	hi("Question", { fg = c.foreground, bg = c.background, bold = true })

	-- Completion menu
	hi("Pmenu", { fg = c.foreground, bg = c.dim_background })
	hi("PmenuSel", { fg = c.foreground, bg = c.darker_background, bold = true })
	hi("PmenuSbar", { bg = c.dim_background })
	hi("PmenuThumb", { bg = c.foreground })
	hi("PmenuKind", { fg = c.foreground, bg = c.dim_background })
	hi("PmenuKindSel", { fg = c.foreground, bg = c.darker_background, bold = true })
	hi("PmenuExtra", { fg = c.almost_foreground, bg = c.dim_background })
	hi("PmenuExtraSel", { fg = c.almost_foreground, bg = c.darker_background, bold = true })
	hi("WildMenu", { link = "PmenuSel" })

	-- Floating windows
	hi("NormalFloat", { fg = c.foreground, bg = c.background })
	hi("FloatBorder", { fg = c.foreground, bg = c.background })
	hi("FloatTitle", { fg = c.foreground, bg = c.background, bold = true })
	hi("FloatFooter", { fg = c.almost_foreground, bg = c.background })

	-- Tab line
	hi("TabLine", { fg = c.foreground, bg = c.dim_background })
	hi("TabLineSel", { fg = c.foreground, bg = c.background, bold = true })
	hi("TabLineFill", { fg = c.foreground, bg = c.dim_background })

	-- Statusline
	hi("StatusLine", { fg = c.foreground, bg = c.statusline, bold = true })
	hi("StatusLineNC", { fg = c.foreground, bg = c.statusline_inactive })
	hi("StatusLineSeparator", { fg = c.foreground, bg = c.dim_background })

	-- Winbar
	hi("WinBar", { fg = c.foreground, bg = c.background })
	hi("WinBarNC", { fg = c.foreground, bg = c.dim_background })
	hi("WinBarSeparator", { fg = c.foreground, bg = c.background })

	-- Diff
	hi("DiffDelete", { fg = c.error, bg = c.dim_background })
	hi("DiffAdd", { fg = c.info, bg = c.dim_background })
	hi("DiffChange", { fg = c.warning, bg = c.dim_background })
	hi("DiffText", { fg = c.foreground, bg = c.darker_background, bold = true })
	hi("diffAdded", { fg = c.info })
	hi("diffRemoved", { fg = c.error })
	hi("diffChanged", { fg = c.warning })
	hi("diffFile", { fg = c.foreground, bold = true })
	hi("diffNewFile", { fg = c.info, bold = true })
	hi("diffOldFile", { fg = c.error, bold = true })
	hi("diffLine", { fg = c.hint })
	hi("diffIndexLine", { fg = c.almost_foreground })

	-- Syntax (legacy vim groups)
	hi("Comment", { fg = c.foreground, bold = true })
	hi("String", { fg = c.foreground, bold = true })
	hi("Character", { fg = c.foreground, bold = true })
	hi("Number", { fg = c.foreground })
	hi("Float", { fg = c.foreground })
	hi("Boolean", { fg = c.foreground })
	hi("Constant", { fg = c.foreground })
	hi("Identifier", { fg = c.foreground })
	hi("Function", { fg = c.foreground })
	hi("Statement", { fg = c.foreground })
	hi("Conditional", { fg = c.foreground })
	hi("Repeat", { fg = c.foreground })
	hi("Label", { fg = c.foreground })
	hi("Keyword", { fg = c.foreground })
	hi("KeyWord", { link = "Keyword" })
	hi("Exception", { fg = c.foreground })
	hi("PreProc", { fg = c.foreground })
	hi("Include", { fg = c.foreground })
	hi("Define", { fg = c.foreground })
	hi("Macro", { fg = c.foreground })
	hi("PreCondit", { fg = c.foreground })
	hi("Type", { fg = c.foreground })
	hi("StorageClass", { fg = c.foreground })
	hi("Structure", { fg = c.foreground })
	hi("Typedef", { fg = c.foreground })
	hi("Special", { fg = c.foreground })
	hi("SpecialChar", { fg = c.foreground, bold = true })
	hi("Tag", { fg = c.foreground })
	hi("SpecialComment", { fg = c.foreground, bold = true })
	hi("Debug", { fg = c.foreground })
	hi("Delimiter", { fg = c.foreground })
	hi("Operator", { fg = c.foreground })
	hi("Underlined", { fg = c.hint, underline = true })
	hi("Ignore", { fg = c.almost_foreground })
	hi("Error", { fg = c.error, bold = true })
	hi("Todo", { fg = c.foreground, bold = true })

	-- Treesitter (modern captures, see :h treesitter-highlight-groups)
	-- Identifiers
	hi("@variable", { fg = c.foreground })
	hi("@variable.builtin", { fg = c.foreground, italic = true })
	hi("@variable.parameter", { fg = c.foreground, italic = true })
	hi("@variable.parameter.builtin", { fg = c.foreground, italic = true })
	hi("@variable.member", { fg = c.foreground })
	hi("@constant", { fg = c.foreground })
	hi("@constant.builtin", { fg = c.foreground, italic = true })
	hi("@constant.macro", { fg = c.foreground })
	hi("@module", { fg = c.foreground })
	hi("@module.builtin", { fg = c.foreground, italic = true })
	hi("@label", { fg = c.foreground })

	-- Literals
	hi("@string", { fg = c.foreground, bold = true })
	hi("@string.documentation", { fg = c.foreground, bold = true })
	hi("@string.regexp", { fg = c.foreground, bold = true })
	hi("@string.escape", { fg = c.foreground, bold = true })
	hi("@string.special", { fg = c.foreground, bold = true })
	hi("@string.special.symbol", { fg = c.foreground, bold = true })
	hi("@string.special.url", { fg = c.hint, underline = true })
	hi("@string.special.path", { fg = c.foreground, underline = true })
	hi("@character", { fg = c.foreground, bold = true })
	hi("@character.special", { fg = c.foreground, bold = true })
	hi("@boolean", { fg = c.foreground })
	hi("@number", { fg = c.foreground })
	hi("@number.float", { fg = c.foreground })

	-- Types
	hi("@type", { fg = c.foreground })
	hi("@type.builtin", { fg = c.foreground, italic = true })
	hi("@type.definition", { fg = c.foreground, bold = true })
	hi("@attribute", { fg = c.foreground })
	hi("@attribute.builtin", { fg = c.foreground, italic = true })
	hi("@property", { fg = c.foreground })

	-- Functions
	hi("@function", { fg = c.foreground })
	hi("@function.builtin", { fg = c.foreground, italic = true })
	hi("@function.call", { fg = c.foreground })
	hi("@function.macro", { fg = c.foreground })
	hi("@function.method", { fg = c.foreground })
	hi("@function.method.call", { fg = c.foreground })
	hi("@constructor", { fg = c.foreground })
	hi("@operator", { fg = c.foreground })

	-- Keywords
	hi("@keyword", { link = "Keyword" })
	hi("@keyword.coroutine", { fg = c.foreground })
	hi("@keyword.function", { fg = c.foreground })
	hi("@keyword.operator", { fg = c.foreground })
	hi("@keyword.import", { fg = c.foreground })
	hi("@keyword.type", { fg = c.foreground })
	hi("@keyword.modifier", { fg = c.foreground })
	hi("@keyword.repeat", { fg = c.foreground })
	hi("@keyword.return", { fg = c.foreground })
	hi("@keyword.debug", { fg = c.warning })
	hi("@keyword.exception", { fg = c.foreground })
	hi("@keyword.conditional", { fg = c.foreground })
	hi("@keyword.conditional.ternary", { fg = c.foreground })
	hi("@keyword.directive", { fg = c.foreground })
	hi("@keyword.directive.define", { fg = c.foreground })

	-- Punctuation
	hi("@punctuation", { fg = c.foreground })
	hi("@punctuation.delimiter", { fg = c.foreground })
	hi("@punctuation.bracket", { fg = c.foreground })
	hi("@punctuation.special", { fg = c.foreground })

	-- Comments
	hi("@comment", { fg = c.foreground, bold = true })
	hi("@comment.documentation", { fg = c.foreground, bold = true })
	hi("@comment.error", { fg = c.error, bold = true })
	hi("@comment.warning", { fg = c.warning, bold = true })
	hi("@comment.todo", { fg = c.hint, bold = true })
	hi("@comment.note", { fg = c.info, bold = true })

	-- Markup
	hi("@markup", { fg = c.foreground })
	hi("@markup.strong", { fg = c.foreground, bold = true })
	hi("@markup.italic", { fg = c.foreground, italic = true })
	hi("@markup.strikethrough", { fg = c.foreground, strikethrough = true })
	hi("@markup.underline", { fg = c.foreground, underline = true })
	hi("@markup.heading", { fg = c.foreground, bold = true })
	hi("@markup.heading.1", { fg = c.foreground, bold = true })
	hi("@markup.heading.2", { fg = c.foreground, bold = true })
	hi("@markup.heading.3", { fg = c.foreground, bold = true })
	hi("@markup.heading.4", { fg = c.foreground, bold = true })
	hi("@markup.heading.5", { fg = c.foreground, bold = true })
	hi("@markup.heading.6", { fg = c.foreground, bold = true })
	hi("@markup.quote", { fg = c.foreground, italic = true })
	hi("@markup.math", { fg = c.foreground })
	hi("@markup.environment", { fg = c.foreground })
	hi("@markup.link", { fg = c.hint })
	hi("@markup.link.label", { fg = c.hint, underline = true })
	hi("@markup.link.url", { fg = c.hint, underline = true })
	hi("@markup.raw", { fg = c.foreground, bold = true })
	hi("@markup.raw.block", { fg = c.foreground, bg = c.dim_background })
	hi("@markup.list", { fg = c.foreground, bold = true })
	hi("@markup.list.checked", { fg = c.info, bold = true })
	hi("@markup.list.unchecked", { fg = c.foreground, bold = true })

	-- Diff
	hi("@diff.plus", { fg = c.info })
	hi("@diff.minus", { fg = c.error })
	hi("@diff.delta", { fg = c.warning })

	-- Tags (HTML/XML/JSX)
	hi("@tag", { fg = c.foreground, bold = true })
	hi("@tag.builtin", { fg = c.foreground, bold = true })
	hi("@tag.attribute", { fg = c.foreground, italic = true })
	hi("@tag.delimiter", { fg = c.foreground })

	-- LSP semantic tokens (see :h lsp-semantic-highlight)
	hi("@lsp.type.class", { link = "@type" })
	hi("@lsp.type.comment", { link = "@comment" })
	hi("@lsp.type.decorator", { link = "@attribute" })
	hi("@lsp.type.enum", { link = "@type" })
	hi("@lsp.type.enumMember", { link = "@constant" })
	hi("@lsp.type.event", { link = "@type" })
	hi("@lsp.type.function", { link = "@function" })
	hi("@lsp.type.interface", { link = "@type" })
	hi("@lsp.type.keyword", { link = "@keyword" })
	hi("@lsp.type.macro", { link = "@constant.macro" })
	hi("@lsp.type.method", { link = "@function.method" })
	hi("@lsp.type.modifier", { link = "@keyword.modifier" })
	hi("@lsp.type.namespace", { link = "@module" })
	hi("@lsp.type.number", { link = "@number" })
	hi("@lsp.type.operator", { link = "@operator" })
	hi("@lsp.type.parameter", { link = "@variable.parameter" })
	hi("@lsp.type.property", { link = "@property" })
	hi("@lsp.type.regexp", { link = "@string.regexp" })
	hi("@lsp.type.string", { link = "@string" })
	hi("@lsp.type.struct", { link = "@type" })
	hi("@lsp.type.type", { link = "@type" })
	hi("@lsp.type.typeParameter", { link = "@type.definition" })
	hi("@lsp.type.variable", { link = "@variable" })
	hi("@lsp.mod.deprecated", { strikethrough = true })
	hi("@lsp.mod.readonly", { italic = true })
	hi("@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
	hi("@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
	hi("@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })

	-- Diagnostics
	hi("DiagnosticError", { fg = c.error })
	hi("DiagnosticWarn", { fg = c.warning })
	hi("DiagnosticInfo", { fg = c.info })
	hi("DiagnosticHint", { fg = c.hint })
	hi("DiagnosticOk", { fg = c.info })
	hi("DiagnosticVirtualTextError", { fg = c.error, bg = c.background, italic = true })
	hi("DiagnosticVirtualTextWarn", { fg = c.warning, bg = c.background, italic = true })
	hi("DiagnosticVirtualTextInfo", { fg = c.info, bg = c.background, italic = true })
	hi("DiagnosticVirtualTextHint", { fg = c.hint, bg = c.background, italic = true })
	hi("DiagnosticVirtualTextOk", { fg = c.info, bg = c.background, italic = true })
	hi("DiagnosticUnderlineError", { undercurl = true, sp = c.error })
	hi("DiagnosticUnderlineWarn", { undercurl = true, sp = c.warning })
	hi("DiagnosticUnderlineInfo", { undercurl = true, sp = c.info })
	hi("DiagnosticUnderlineHint", { undercurl = true, sp = c.hint })
	hi("DiagnosticUnderlineOk", { undercurl = true, sp = c.info })
	hi("DiagnosticSignError", { fg = c.error, bg = c.dim_background })
	hi("DiagnosticSignWarn", { fg = c.warning, bg = c.dim_background })
	hi("DiagnosticSignInfo", { fg = c.info, bg = c.dim_background })
	hi("DiagnosticSignHint", { fg = c.hint, bg = c.dim_background })
	hi("DiagnosticSignOk", { fg = c.info, bg = c.dim_background })
	hi("DiagnosticFloatingError", { fg = c.error, bg = c.background })
	hi("DiagnosticFloatingWarn", { fg = c.warning, bg = c.background })
	hi("DiagnosticFloatingInfo", { fg = c.info, bg = c.background })
	hi("DiagnosticFloatingHint", { fg = c.hint, bg = c.background })
	hi("DiagnosticFloatingOk", { fg = c.info, bg = c.background })
	hi("DiagnosticDeprecated", { fg = c.almost_foreground, strikethrough = true })
	hi("DiagnosticUnnecessary", { fg = c.almost_foreground })

	-- LSP UI
	hi("LspReferenceText", { bg = c.darker_background })
	hi("LspReferenceRead", { bg = c.darker_background })
	hi("LspReferenceWrite", { bg = c.darker_background, bold = true })
	hi("LspSignatureActiveParameter", { fg = c.foreground, bg = c.darker_background, bold = true })
	hi("LspCodeLens", { fg = c.almost_foreground, italic = true })
	hi("LspCodeLensSeparator", { fg = c.almost_foreground })
	hi("LspInlayHint", { fg = c.almost_foreground, bg = c.dim_background, italic = true })
end

return M
